import type { MetadataRoute } from 'next';

/**
 * Web app manifest (Story 7.3 AC1 / Task 1.1). Next.js serves this at
 * `/manifest.webmanifest` from the `app/manifest.ts` metadata-file convention.
 *
 * Colours are the literal values of the design tokens (a manifest cannot
 * reference CSS custom properties): `theme_color` is `--color-amber-primary`
 * (the brand amber) and `background_color` is `--color-surface-cream` (the
 * app's resting surface, used for the standalone splash). Keep these in sync
 * with `app/globals.css` if the tokens change.
 *
 * Icons are token-derived placeholder marks generated by
 * `scripts/generate-pwa-icons.mjs` (no source brand mark exists yet); swap
 * them for a real mark when one is produced. App-shell only — no offline data
 * caching (real-time sun predictions require connectivity).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'SunnySeat',
    short_name: 'SunnySeat',
    description: 'Hitta soliga uteserveringar i Göteborg',
    start_url: '/',
    display: 'standalone',
    background_color: '#fdfaf4', // --color-surface-cream
    theme_color: '#ffbf00', // --color-amber-primary
    icons: [
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
