-- Story 12.1: Place-ID-only, provider-neutral opening-hours governance.
-- Canonical public hours remain public.venues.opening_hours (nullable jsonb).
-- Provenance and review operations are service-only and never projected into
-- public DTOs. Existing rows remain deployable before the one-time remediation:
-- provenance fields are nullable and no old schedule is relabelled automatically.

alter table public.venues
  drop column if exists places_api_url,
  add column if not exists hours_source_type text,
  add column if not exists hours_source_reference text,
  add column if not exists hours_review_status text,
  add column if not exists hours_reviewed_at timestamptz,
  add column if not exists hours_next_review_at timestamptz,
  add column if not exists hours_notes text;

alter table public.venues
  alter column opening_hours drop not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'venues_hours_source_type_check'
      and conrelid = 'public.venues'::regclass
  ) then
    alter table public.venues add constraint venues_hours_source_type_check
      check (
        hours_source_type is null or hours_source_type in (
          'venue_confirmed',
          'venue_website',
          'licensed_provider',
          'manual'
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'venues_hours_review_status_check'
      and conrelid = 'public.venues'::regclass
  ) then
    alter table public.venues add constraint venues_hours_review_status_check
      check (
        hours_review_status is null or hours_review_status in (
          'verified',
          'due',
          'manual_review',
          'unknown',
          'failed'
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'venues_hours_review_dates_check'
      and conrelid = 'public.venues'::regclass
  ) then
    alter table public.venues add constraint venues_hours_review_dates_check
      check (
        hours_next_review_at is null
        or hours_reviewed_at is null
        or hours_next_review_at >= hours_reviewed_at
      );
  end if;
end
$$;

create index if not exists venues_place_id_idx
  on public.venues (place_id)
  where place_id is not null;

create index if not exists venues_hours_next_review_at_idx
  on public.venues (hours_next_review_at)
  where hours_next_review_at is not null;

create table if not exists public.hours_review_runs (
  id text primary key,
  trigger_type text not null,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  total_count integer not null default 0 check (total_count >= 0),
  current_count integer not null default 0 check (current_count >= 0),
  missing_provenance_count integer not null default 0 check (missing_provenance_count >= 0),
  due_count integer not null default 0 check (due_count >= 0),
  unknown_count integer not null default 0 check (unknown_count >= 0),
  conflicting_count integer not null default 0 check (conflicting_count >= 0),
  split_count integer not null default 0 check (split_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  stale_count integer not null default 0 check (stale_count >= 0),
  constraint hours_review_runs_trigger_type_check
    check (trigger_type in ('scheduled', 'manual', 'remediation')),
  constraint hours_review_runs_status_check
    check (status in ('running', 'completed', 'completed_with_failures', 'failed')),
  constraint hours_review_runs_finished_at_check
    check ((status = 'running' and finished_at is null) or (status <> 'running' and finished_at is not null))
);

create table if not exists public.hours_review_outcomes (
  id bigint generated by default as identity primary key,
  run_id text not null references public.hours_review_runs(id) on delete cascade,
  venue_id text not null references public.venues(id) on delete cascade,
  venue_slug text not null check (char_length(venue_slug) between 1 and 200),
  outcome text not null,
  reason text not null,
  error_class text,
  created_at timestamptz not null default now(),
  constraint hours_review_outcomes_run_venue_key unique (run_id, venue_id),
  constraint hours_review_outcomes_outcome_check
    check (outcome in (
      'current',
      'missing_provenance',
      'due',
      'unknown',
      'conflicting',
      'split',
      'failed',
      'stale'
    )),
  constraint hours_review_outcomes_reason_check
    check (reason in (
      'review_current',
      'missing_provenance',
      'review_due',
      'hours_unknown',
      'provenance_conflict',
      'unsupported_split',
      'prior_failure',
      'review_stale',
      'classification_failed'
    )),
  constraint hours_review_outcomes_error_class_check
    check (
      error_class is null or error_class in (
        'read_failed',
        'validation_failed',
        'database_error',
        'unexpected'
      )
    )
);

create index if not exists hours_review_runs_started_at_idx
  on public.hours_review_runs (started_at desc);

create index if not exists hours_review_outcomes_run_id_idx
  on public.hours_review_outcomes (run_id);

create index if not exists hours_review_outcomes_venue_id_created_at_idx
  on public.hours_review_outcomes (venue_id, created_at desc);

-- Atomic non-overlap: at most one active run may hold status='running'. The
-- partial unique index makes the claim race-safe across independent workers.
create unique index if not exists hours_review_runs_one_active_run_idx
  on public.hours_review_runs ((status))
  where status = 'running';

alter table public.hours_review_runs enable row level security;
alter table public.hours_review_runs force row level security;
alter table public.hours_review_outcomes enable row level security;
alter table public.hours_review_outcomes force row level security;

revoke all on table public.hours_review_runs from public;
revoke all on table public.hours_review_runs from anon;
revoke all on table public.hours_review_runs from authenticated;
revoke all on table public.hours_review_runs from service_role;
revoke all on table public.hours_review_outcomes from public;
revoke all on table public.hours_review_outcomes from anon;
revoke all on table public.hours_review_outcomes from authenticated;
revoke all on table public.hours_review_outcomes from service_role;
revoke all on sequence public.hours_review_outcomes_id_seq from public;
revoke all on sequence public.hours_review_outcomes_id_seq from anon;
revoke all on sequence public.hours_review_outcomes_id_seq from authenticated;
revoke all on sequence public.hours_review_outcomes_id_seq from service_role;

grant select, insert, update, delete on table public.hours_review_runs to service_role;
grant select, insert, update on table public.hours_review_outcomes to service_role;
grant usage on sequence public.hours_review_outcomes_id_seq to service_role;

create or replace function public.claim_hours_review_run(
  p_run_id text,
  p_trigger_type text,
  p_started_at timestamptz default now()
)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  inserted_count integer;
begin
  insert into public.hours_review_runs (id, trigger_type, status, started_at)
  values (p_run_id, p_trigger_type, 'running', p_started_at)
  on conflict do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

create or replace function public.finish_hours_review_run(
  p_run_id text,
  p_status text,
  p_finished_at timestamptz,
  p_total_count integer,
  p_current_count integer,
  p_missing_provenance_count integer,
  p_due_count integer,
  p_unknown_count integer,
  p_conflicting_count integer,
  p_split_count integer,
  p_failed_count integer,
  p_stale_count integer
)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  update public.hours_review_runs
  set status = p_status,
      finished_at = p_finished_at,
      total_count = p_total_count,
      current_count = p_current_count,
      missing_provenance_count = p_missing_provenance_count,
      due_count = p_due_count,
      unknown_count = p_unknown_count,
      conflicting_count = p_conflicting_count,
      split_count = p_split_count,
      failed_count = p_failed_count,
      stale_count = p_stale_count
  where id = p_run_id and status = 'running';

  return found;
end;
$$;

create or replace function public.prune_hours_review_history(
  p_cutoff timestamptz default (now() - interval '180 days')
)
returns integer
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  deleted_count integer;
begin
  delete from public.hours_review_runs
  where coalesce(finished_at, started_at) < p_cutoff
    and status <> 'running';

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.claim_hours_review_run(text, text, timestamptz) from public;
revoke all on function public.claim_hours_review_run(text, text, timestamptz) from anon;
revoke all on function public.claim_hours_review_run(text, text, timestamptz) from authenticated;
revoke all on function public.finish_hours_review_run(text, text, timestamptz, integer, integer, integer, integer, integer, integer, integer, integer, integer) from public;
revoke all on function public.finish_hours_review_run(text, text, timestamptz, integer, integer, integer, integer, integer, integer, integer, integer, integer) from anon;
revoke all on function public.finish_hours_review_run(text, text, timestamptz, integer, integer, integer, integer, integer, integer, integer, integer, integer) from authenticated;
revoke all on function public.prune_hours_review_history(timestamptz) from public;
revoke all on function public.prune_hours_review_history(timestamptz) from anon;
revoke all on function public.prune_hours_review_history(timestamptz) from authenticated;

grant execute on function public.claim_hours_review_run(text, text, timestamptz) to service_role;
grant execute on function public.finish_hours_review_run(text, text, timestamptz, integer, integer, integer, integer, integer, integer, integer, integer, integer) to service_role;
grant execute on function public.prune_hours_review_history(timestamptz) to service_role;

comment on column public.venues.place_id is
  'Server-only Google Place ID identity/reference metadata. No provider content is persisted.';
comment on table public.hours_review_runs is
  'Service-only bounded audit summaries; retained for 180 days.';
comment on table public.hours_review_outcomes is
  'Service-only per-venue classifications without provider payloads or source content.';

