-- Story 12.1 review iteration 2: close the remaining coherence, lease,
-- idempotency, and drift-replay gaps. Deliberately retains
-- hours_review_outcomes.venue_id ON DELETE CASCADE per maintainer decision.

-- Converge any live partial-table drift that predates the now-hardened initial
-- forward migration. A healthy deployment is already bigint identity `d` and
-- takes the no-op branch.
do $$
declare
  identity_kind text;
  id_type regtype;
  old_sequence text;
  new_sequence text;
  max_id bigint;
begin
  select attidentity, atttypid::regtype
  into identity_kind, id_type
  from pg_attribute
  where attrelid = 'public.hours_review_outcomes'::regclass
    and attname = 'id'
    and not attisdropped;

  if id_type <> 'bigint'::regtype then
    alter table public.hours_review_outcomes
      alter column id type bigint using id::bigint;
  end if;

  if identity_kind = '' then
    select coalesce(max(id), 0) into max_id
    from public.hours_review_outcomes;
    with missing as (
      select ctid, row_number() over (order by ctid) as ordinal
      from public.hours_review_outcomes
      where id is null
    )
    update public.hours_review_outcomes o
    set id = max_id + missing.ordinal
    from missing
    where o.ctid = missing.ctid;
    alter table public.hours_review_outcomes alter column id set not null;

    old_sequence := pg_get_serial_sequence(
      'public.hours_review_outcomes',
      'id'
    );
    alter table public.hours_review_outcomes alter column id drop default;
    if old_sequence is not null then
      execute format('drop sequence if exists %s', old_sequence);
    end if;
    alter table public.hours_review_outcomes
      alter column id add generated by default as identity;
  end if;

  select max(id) into max_id from public.hours_review_outcomes;
  new_sequence := pg_get_serial_sequence(
    'public.hours_review_outcomes',
    'id'
  );
  if max_id is not null then
    perform setval(new_sequence::regclass, max_id, true);
  end if;
end
$$;

-- Fail closed for any pre-existing public schedule that still lacks complete
-- independent evidence. Persist a bounded migration outcome before clearing
-- it so constraint validation never silently discards an affected venue.
drop table if exists pg_temp.story_12_1_incoherent_venues;
create temporary table story_12_1_incoherent_venues as
select id, slug, hours_review_status as prior_review_status
from public.venues
where (
    opening_hours is not null
    and not (
      hours_source_type is not null
      and hours_source_reference is not null
      and btrim(hours_source_reference) <> ''
      and hours_review_status is not null
      and hours_review_status in ('verified', 'due', 'manual_review', 'failed')
      and hours_reviewed_at is not null
      and hours_next_review_at is not null
    )
  )
  or (hours_source_reference is not null and btrim(hours_source_reference) = '');

insert into public.hours_review_runs (
  id,
  trigger_type,
  status,
  started_at,
  finished_at,
  lease_expires_at,
  total_count,
  unknown_count
)
select
  'hours-coherence-migration-20260714131540',
  'remediation',
  'completed',
  statement_timestamp(),
  statement_timestamp(),
  statement_timestamp(),
  count(*)::integer,
  count(*)::integer
from story_12_1_incoherent_venues
having count(*) > 0
on conflict (id) do nothing;

insert into public.hours_review_outcomes (
  run_id,
  venue_id,
  venue_slug,
  outcome,
  reason,
  error_class,
  prior_review_status,
  resulting_review_status
)
select
  'hours-coherence-migration-20260714131540',
  id,
  slug,
  'unknown',
  'hours_unknown',
  null,
  prior_review_status,
  'unknown'
from story_12_1_incoherent_venues
on conflict (run_id, venue_id) do nothing;

update public.venues v
set opening_hours = null,
    hours_source_type = null,
    hours_source_reference = null,
    hours_review_status = 'unknown',
    hours_reviewed_at = null,
    hours_next_review_at = null,
    hours_review_reason = null,
    hours_last_error_class = null
from story_12_1_incoherent_venues i
where v.id = i.id;

alter table public.venues
  drop constraint if exists venues_hours_source_reference_policy_check,
  drop constraint if exists venues_hours_notes_policy_check,
  drop constraint if exists venues_hours_review_reason_check,
  drop constraint if exists venues_hours_state_coherence_check;

alter table public.venues
  add constraint venues_hours_source_reference_policy_check
    check (
      hours_source_reference is null
      or (
        char_length(hours_source_reference) between 1 and 500
        and btrim(hours_source_reference) <> ''
        and hours_source_reference !~ E'[\r\n]'
        and hours_source_reference !~* '(https?://|www\.|provider-payload|regular.?opening.?hours|(^|[?&;:_-])(api[_-]?key|key|token|secret)=)'
      )
    ) not valid,
  add constraint venues_hours_notes_policy_check
    check (
      hours_notes is null
      or (
        char_length(hours_notes) <= 1000
        and hours_notes !~* '(https?://|www\.|provider[[:space:]_-]*payload|regular[[:space:]_-]*opening[[:space:]_-]*hours|(^|[?&;:[:space:]_-])(api[_-]?key|key|token|secret)[[:space:]]*=)'
      )
    ) not valid,
  add constraint venues_hours_review_reason_check
    check (
      hours_review_reason is null
      or hours_review_reason in (
        'provenance_conflict',
        'unsupported_split',
        'unsupported_24_7',
        'unsupported_seasonal',
        'unsupported_holiday_specific',
        'classification_failed'
      )
    ) not valid,
  add constraint venues_hours_state_coherence_check
    check (
      (
        opening_hours is null
        or (
          hours_source_type is not null
          and hours_source_reference is not null
          and btrim(hours_source_reference) <> ''
          and hours_review_status is not null
          and hours_review_status in ('verified', 'due', 'manual_review', 'failed')
          and hours_reviewed_at is not null
          and hours_next_review_at is not null
        )
      )
      and (hours_review_status is distinct from 'unknown' or opening_hours is null)
      and (
        hours_review_status is distinct from 'manual_review'
        or hours_review_reason is not null
      )
      and (
        hours_review_status is distinct from 'failed'
        or hours_last_error_class is not null
      )
      and (
        hours_review_status is distinct from 'verified'
        or (
          opening_hours is not null
          and hours_review_reason is null
          and hours_last_error_class is null
        )
      )
    ) not valid;

-- Converge persisted run summaries from their child evidence before making
-- the already-declared counter invariant valid for historical rows.
with outcome_counts as (
  select
    r.id,
    count(o.id)::integer as total_count,
    count(*) filter (where o.outcome = 'current')::integer as current_count,
    count(*) filter (where o.outcome = 'missing_provenance')::integer as missing_provenance_count,
    count(*) filter (where o.outcome = 'due')::integer as due_count,
    count(*) filter (where o.outcome = 'unknown')::integer as unknown_count,
    count(*) filter (where o.outcome = 'conflicting')::integer as conflicting_count,
    count(*) filter (where o.outcome = 'split')::integer as split_count,
    count(*) filter (where o.outcome = 'failed')::integer as failed_count,
    count(*) filter (where o.outcome = 'stale')::integer as stale_count
  from public.hours_review_runs r
  left join public.hours_review_outcomes o on o.run_id = r.id
  where r.status <> 'running'
  group by r.id
)
update public.hours_review_runs r
set total_count = c.total_count,
    current_count = c.current_count,
    missing_provenance_count = c.missing_provenance_count,
    due_count = c.due_count,
    unknown_count = c.unknown_count,
    conflicting_count = c.conflicting_count,
    split_count = c.split_count,
    failed_count = c.failed_count,
    stale_count = c.stale_count
from outcome_counts c
where r.id = c.id;

alter table public.hours_review_outcomes
  drop constraint if exists hours_review_outcomes_reason_check,
  drop constraint if exists hours_review_outcomes_values_check,
  drop constraint if exists hours_review_outcomes_coherence_check;

alter table public.hours_review_outcomes
  add constraint hours_review_outcomes_values_check
    check (
      char_length(venue_slug) between 1 and 200
      and outcome in (
        'current', 'missing_provenance', 'due', 'unknown',
        'conflicting', 'split', 'failed', 'stale'
      )
      and reason in (
        'review_current', 'missing_provenance', 'review_due', 'hours_unknown',
        'provenance_conflict', 'unsupported_split', 'unsupported_24_7',
        'unsupported_seasonal', 'unsupported_holiday_specific',
        'prior_failure', 'review_stale', 'classification_failed'
      )
      and (
        error_class is null
        or error_class in (
          'read_failed', 'validation_failed', 'database_error', 'unexpected'
        )
      )
    ) not valid,
  add constraint hours_review_outcomes_coherence_check
    check (
      (outcome = 'current' and reason = 'review_current' and error_class is null)
      or (outcome = 'missing_provenance' and reason = 'missing_provenance' and error_class is null)
      or (outcome = 'due' and reason = 'review_due' and error_class is null)
      or (outcome = 'unknown' and reason = 'hours_unknown' and error_class is null)
      or (outcome = 'conflicting' and reason = 'provenance_conflict' and error_class is null)
      or (outcome = 'split' and reason = 'unsupported_split' and error_class is null)
      or (outcome = 'stale' and reason = 'review_stale' and error_class is null)
      or (
        outcome = 'failed'
        and reason in (
          'prior_failure',
          'classification_failed',
          'unsupported_24_7',
          'unsupported_seasonal',
          'unsupported_holiday_specific'
        )
        and error_class is not null
      )
    ) not valid;

alter table public.venues
  validate constraint venues_hours_source_reference_policy_check,
  validate constraint venues_hours_notes_policy_check,
  validate constraint venues_hours_review_reason_check,
  validate constraint venues_hours_state_coherence_check;

alter table public.hours_review_runs
  validate constraint hours_review_runs_counter_sum_check;

alter table public.hours_review_outcomes
  validate constraint hours_review_outcomes_values_check,
  validate constraint hours_review_outcomes_coherence_check;

-- Finalization compares every caller-supplied counter with an independently
-- derived aggregate and writes the derived values only.
create or replace function public.finish_hours_review_run(
  p_run_id text,
  p_status text,
  p_finished_at timestamptz,
  p_total_count integer,
  p_current_count integer,
  p_missing_provenance_count integer,
  p_due_count integer,
  p_unknown_count integer,
  p_conflicting_count integer,
  p_split_count integer,
  p_failed_count integer,
  p_stale_count integer
)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  c record;
begin
  if p_status not in ('completed', 'completed_with_failures') then
    return false;
  end if;

  select
    count(*)::integer as total_count,
    count(*) filter (where outcome = 'current')::integer as current_count,
    count(*) filter (where outcome = 'missing_provenance')::integer as missing_provenance_count,
    count(*) filter (where outcome = 'due')::integer as due_count,
    count(*) filter (where outcome = 'unknown')::integer as unknown_count,
    count(*) filter (where outcome = 'conflicting')::integer as conflicting_count,
    count(*) filter (where outcome = 'split')::integer as split_count,
    count(*) filter (where outcome = 'failed')::integer as failed_count,
    count(*) filter (where outcome = 'stale')::integer as stale_count
  into c
  from public.hours_review_outcomes
  where run_id = p_run_id;

  if p_total_count <> c.total_count
     or p_current_count <> c.current_count
     or p_missing_provenance_count <> c.missing_provenance_count
     or p_due_count <> c.due_count
     or p_unknown_count <> c.unknown_count
     or p_conflicting_count <> c.conflicting_count
     or p_split_count <> c.split_count
     or p_failed_count <> c.failed_count
     or p_stale_count <> c.stale_count then
    return false;
  end if;

  update public.hours_review_runs
  set status = p_status,
      finished_at = p_finished_at,
      lease_expires_at = p_finished_at,
      total_count = c.total_count,
      current_count = c.current_count,
      missing_provenance_count = c.missing_provenance_count,
      due_count = c.due_count,
      unknown_count = c.unknown_count,
      conflicting_count = c.conflicting_count,
      split_count = c.split_count,
      failed_count = c.failed_count,
      stale_count = c.stale_count
  where id = p_run_id and status = 'running';

  return found;
end;
$$;

create or replace function public.renew_hours_review_run_lease(
  p_run_id text
)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  update public.hours_review_runs
  set lease_expires_at = clock_timestamp() + interval '15 minutes'
  where id = p_run_id
    and trigger_type = 'remediation'
    and status = 'running'
    and lease_expires_at > clock_timestamp();

  return found;
end;
$$;

-- Canonical remediation writes require a live remediation lease. Manual and
-- failed evidence preserve an already independently evidenced schedule and
-- provenance; unproven legacy schedules still fail closed to unknown.
create or replace function public.apply_hours_remediation_outcome(
  p_run_id text,
  p_venue_id text,
  p_venue_slug text,
  p_opening_hours jsonb,
  p_source_type text,
  p_source_reference text,
  p_review_status text,
  p_reviewed_at timestamptz,
  p_next_review_at timestamptz,
  p_notes text,
  p_review_reason text,
  p_last_error_class text,
  p_outcome text,
  p_reason text,
  p_error_class text
)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  prior_status text;
  prior_opening_hours jsonb;
  prior_source_type text;
  prior_source_reference text;
  prior_reviewed_at timestamptz;
  prior_next_review_at timestamptz;
  preserve_verified_schedule boolean;
begin
  perform 1
  from public.hours_review_runs
  where id = p_run_id
    and trigger_type = 'remediation'
    and status = 'running'
    and lease_expires_at > clock_timestamp()
  for update;

  if not found then
    return false;
  end if;

  select
    hours_review_status,
    opening_hours,
    hours_source_type,
    hours_source_reference,
    hours_reviewed_at,
    hours_next_review_at
  into
    prior_status,
    prior_opening_hours,
    prior_source_type,
    prior_source_reference,
    prior_reviewed_at,
    prior_next_review_at
  from public.venues
  where id = p_venue_id
  for update;

  if not found then
    return false;
  end if;

  preserve_verified_schedule :=
    p_review_status in ('manual_review', 'failed')
    and prior_opening_hours is not null
    and prior_source_type is not null
    and prior_source_reference is not null
    and btrim(prior_source_reference) <> ''
    and prior_reviewed_at is not null
    and prior_next_review_at is not null
    and prior_status in ('verified', 'due', 'manual_review', 'failed');

  if preserve_verified_schedule then
    update public.venues
    set hours_review_status = p_review_status,
        hours_notes = p_notes,
        hours_review_reason = p_review_reason,
        hours_last_error_class = p_last_error_class
    where id = p_venue_id;
  else
    update public.venues
    set opening_hours = p_opening_hours,
        hours_source_type = p_source_type,
        hours_source_reference = p_source_reference,
        hours_review_status = p_review_status,
        hours_reviewed_at = p_reviewed_at,
        hours_next_review_at = p_next_review_at,
        hours_notes = p_notes,
        hours_review_reason = p_review_reason,
        hours_last_error_class = p_last_error_class
    where id = p_venue_id;
  end if;

  insert into public.hours_review_outcomes as existing (
    run_id,
    venue_id,
    venue_slug,
    outcome,
    reason,
    error_class,
    prior_review_status,
    resulting_review_status
  ) values (
    p_run_id,
    p_venue_id,
    p_venue_slug,
    p_outcome,
    p_reason,
    p_error_class,
    prior_status,
    p_review_status
  )
  on conflict (run_id, venue_id) do update
  set venue_slug = excluded.venue_slug,
      outcome = excluded.outcome,
      reason = excluded.reason,
      error_class = excluded.error_class,
      prior_review_status = existing.prior_review_status,
      resulting_review_status = excluded.resulting_review_status;

  return true;
end;
$$;

revoke all on function public.finish_hours_review_run(
  text, text, timestamptz,
  integer, integer, integer, integer, integer, integer, integer, integer, integer
) from public, anon, authenticated, service_role;
revoke all on function public.renew_hours_review_run_lease(text)
  from public, anon, authenticated, service_role;
revoke all on function public.apply_hours_remediation_outcome(
  text, text, text, jsonb, text, text, text, timestamptz, timestamptz,
  text, text, text, text, text, text
) from public, anon, authenticated, service_role;

grant execute on function public.finish_hours_review_run(
  text, text, timestamptz,
  integer, integer, integer, integer, integer, integer, integer, integer, integer
) to service_role;
grant execute on function public.renew_hours_review_run_lease(text)
  to service_role;
grant execute on function public.apply_hours_remediation_outcome(
  text, text, text, jsonb, text, text, text, timestamptz, timestamptz,
  text, text, text, text, text, text
) to service_role;

grant update (
  opening_hours,
  hours_source_type,
  hours_source_reference,
  hours_review_status,
  hours_reviewed_at,
  hours_next_review_at,
  hours_notes,
  hours_review_reason,
  hours_last_error_class
) on table public.venues to service_role;

comment on function public.renew_hours_review_run_lease(text) is
  'Extends only an unexpired active remediation lease; canonical writes recheck the same lease.';
