export const SOLAR_CONSTANTS = {
  JULIAN_DAY_2000: 2451545.0,
  DAYS_PER_JULIAN_CENTURY: 36525.0,
  DEG_TO_RAD: Math.PI / 180.0,
  RAD_TO_DEG: 180.0 / Math.PI,
  EARTH_ECCENTRICITY: 0.016708634,
  MEAN_OBLIQUITY: 23.439291,
  ATMOSPHERIC_REFRACTION: 0.5667,
  SOLAR_SEMI_DIAMETER: 0.2667,
  STANDARD_PRESSURE: 1013.25,
  STANDARD_TEMPERATURE: 15.0,
  MAX_CALCULATION_ERROR: 0.01,
  MAX_CALCULATION_TIME_MS: 1.0,
} as const;

export const GOTHENBURG: {
  LATITUDE: number;
  LONGITUDE: number;
  ELEVATION: number;
  TIMEZONE: string;
  MIN_LATITUDE: number;
  MAX_LATITUDE: number;
  MIN_LONGITUDE: number;
  MAX_LONGITUDE: number;
} = {
  LATITUDE: 57.7089,
  LONGITUDE: 11.9746,
  ELEVATION: 12.0,
  TIMEZONE: 'Europe/Stockholm',
  MIN_LATITUDE: 57.6,
  MAX_LATITUDE: 57.8,
  MIN_LONGITUDE: 11.8,
  MAX_LONGITUDE: 12.1,
};

export function isWithinGothenburgBounds(lat: number, lng: number): boolean {
  return (
    lat >= GOTHENBURG.MIN_LATITUDE &&
    lat <= GOTHENBURG.MAX_LATITUDE &&
    lng >= GOTHENBURG.MIN_LONGITUDE &&
    lng <= GOTHENBURG.MAX_LONGITUDE
  );
}
